name: CI
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -r requirements.txt
      - run: python tools/validate.py samples/*.yaml